### ISSUE TITLE
Livewire: Multiple root elements detected. This is not supported

### ISSUE THREAD

**Issue by ArtMin96** [STAFE-GROUP-AB/filament-sticky-panel#1]
I don't know what the problem is, but this warning is displayed in the console.
`Livewire: Multiple root elements detected. This is not supported.`

**Comment by andreaskviby** [comment]
Hey,
Can you please screenshot it and what Livewire component have you added.

**Comment by ArtMin96** [comment]
Hi. Sorry, the problem was coming from another component that had the same class attribute.
